-- 코드를 입력하세요
# HOUR 함수를 사용해 DATETIME 형식을 시간 형식으로 변경
SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) <= 19
GROUP BY HOUR 
ORDER BY HOUR; # 시간대 순 정렬